version: "3"
services:
  mysql:
    image: mysql
    container_name: "mysql"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=diploma
    ports:
      - 3306:3306
  server:
    image: server
    build:
      context: ./server
    volumes:
      - ./server:/usr/src/server
    ports:
      - "5000:5000"
    links:
      - mysql
    depends_on:
      - mysql
  client:
    image: client
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/client
    ports:
      - "3000:3000"
    depends_on:
      - mysql